model:
  base_learning_rate: 2.0e-5
  target: ldm.models.diffusion.mri_ldm.MRILatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    scale_by_std: True
    monitor: 'train/loss_c01_frq_real_low_ema'
    parameterization: 'x0'
    saved_path: <directory_for_visualization>
    mask_stage: 'None'
    mask_strategy: 'None'
    m_ratio: 0.5
    max_rectangles: 256

    rlfs_ratio: 0.10
    frq_mask_ratio: 0.10
    stage1: True
    use_prior: False
    # use_prior: True
    cond_stage_trainable: True
    conditioning_key: concat
    cond_stage_forward: remove_low_frequency_add_noise
    cond_stage_config: 
      target: ldm.modules.mri_modules.MRICrossFusion
      params:
        image_size: 32
        n_embed: 4
        n_layer: 8
        n_channels: 4
        n_prior_head: 128
        frq_mask_ratio: 0.10

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 12
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1, 2, 2, 4, 4]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.mri_vae.MRIVAE
      params:
        ckpt_path: <path_to_vae_ckpt> #"VAE_kl_32x32x4_ckpt/checkpoints/epoch=000xxx.ckpt"
        embed_dim: 4
        monitor: "val/rec_loss"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1, 2, 4, 4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    wrap: False
    train:
      target: ldm.data.mri.MRIIXITrain
      params:
        data_root: # 'xxxx/preprocessing/v2skullstripped/<dataset>/t2_train'
        size: 256
    validation:
      target: ldm.data.mri.MRIIXIValidation
      params:
        data_root: # 'xxxx/preprocessing/v2skullstripped/<dataset>/t2_val'
        size: 256
    test:
      target: ldm.data.mri.MRITest
      params:
        data_root: # 'xxxx/preprocessing/v2skullstripped/<dataset>/t2_test'
        size: 256
        is_test: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 50000
        max_images: 8
        increase_log_steps: False
